#!/usr/bin/php

#requires: sudo apt-get install php5-cli

<?php

if( count($argv) != 4 )
{
	echo "Usage $argv[0] <gdb filename> <addr of text> <addr of pc>\n";
	echo "Example $argv[0] 0x123 0x345\n";
	exit(-1);
}

$gdb_filename = $argv[1];
$text = $argv[2];
$pc = $argv[3];

$pc = '0x' . dechex($pc-$text);

$str = exec("bfin-uclinux-addr2line -f -e $gdb_filename $pc");

$pc2 = substr($pc, 2);
system("bfin-uclinux-objdump -dS $gdb_filename | grep -B 15 -A 15 \ ".$pc2.":");
echo "\n\n\n$gdb_filename stopped at $str -- pc = $pc\n\n\n";

?>