#!/bin/sh
# set this for subcalls
export SCRIPTSDIR="/usr/scripts"
#sleep 1
modprobe ds2482 force=0,0x18

#sleep 1
#mount /dev/mmc2 /mnt/mmc2
#mount -t msdos -o sync /dev/mmc1 /mnt/mmc1
#mount -t msdos -o sync /dev/mmc2 /mnt/mmc2
#mount -t msdos -o sync /dev/mmc3 /mnt/mmc3

echo "Insmod in progress.."
insmod ./w1_analog.ko
insmod ./w1_therm.ko
insmod ./gold_lcd.ko
#insmod ./bfin_twi_lcd.ko
#insmod ./i2c_knob.ko
sleep 4  #if less delay you have to wait for sensor ntw to start anyway
echo "Starting Josefin.."
#cat /etc/motd

./Josefin&

#/usr/Josefin
#/mnt/mmc/Josefin
#cat /etc/issue


exit 0
